export * from "./download/download.component"
export * from "./encoding-messages/encoding-messages.component"
export * from "./learing/learing.component"
export * from "./menu/menu.component"
export * from "./step-by-step/step-by-step.component"
export * from "./translation/translation.component"
export * from "./binary-learning/binary-learning.component"
export * from "./text-learning/text-learning.component"